### ISSUE TITLE
struct.error on ancast.py

### ISSUE THREAD

**Issue by billy-acuna** [hexkyz/hexFW#2]
I'm using Python 2.7 + pyCrypto. Currently using a MinGW envoirement.

C:\wiiu\hexFW-master\firmware>make
Traceback (most recent call last):
  File "scripts/anpack.py", line 255, in <module>
    fw = ancast(open(input_fn, "r+b"))
  File "scripts/anpack.py", line 153, in __init__
    self.elf = elf32(file, len(self.header))
  File "scripts/anpack.py", line 98, in __init__
    self.phdrs = [elf32_phdr(file, offset, self.hdr, i) for i in range(self.hdr.
e_phnum)]
  File "scripts/anpack.py", line 57, in __init__
    self.p_type = struct.unpack(">I", file.read(4))[0]
struct.error: unpack requires a string argument of length 4
make: *** [patches/sections/0x08120000.bin] Error 1

Edid: Nevermind, I was using a bad dump of the fw.img

**Comment by jorgehntx** [comment]
Can i compile this on linux? And i gonna need somethings extra?
